port: auto
baud-rate: 9600
apps:
    - master
    - opera.exe
    - discord.exe
    - AMPLibraryAgent.exe
    - game:
          - geometrydash.exe
          - rustclient.exe
          - ForzaHorizon5.exe
